### ISSUE TITLE
Ця дія потрібна якщо ви будете робити зсув в циклі .  Так к ви застовсували зрізи - то звістно завого елементу створювати не треба

### ISSUE THREAD

**Issue by Muxamedin** [xDarkin/HW_GitHub#1]
https://github.com/xDarkin/HW_GitHub/blob/e3c4a8953d35b982b7c9703da326c0dd23951ae1/lesson_7/task_2.py#L8
уявімо є список 

[1, 2,3,4]
ми додамо якись елемент в кінець методом append() 
[1, 2,3,4, "New element"]
отримали індекс куди вставити якесь нове значення 
k = 2
в цикл зсуваємо елемент в право на 1 від k 
[1, 2,3,3,4]
затираючи останній
підставивши значення до списку за  індексом 2 
матимемо  
[1, 2,"your value",3,4]

**Comment by xDarkin** [comment]
Теперь ясно. А я все не мог понять зачем там append(). Но раз написано, то сделал)
Исправил.
