### ISSUE TITLE
Не вірно підраховується кількість унікальних чисел 

### ISSUE THREAD

**Issue by Muxamedin** [xDarkin/HW_GitHub#2]
https://github.com/xDarkin/HW_GitHub/blob/e61f0f97501d0623c92446abc97f8970f930d2ab/lesson_7/task_3.py#L11

<img width="516" alt="image" src="https://user-images.githubusercontent.com/4419752/183915222-1262df12-82be-44f3-90be-dac42ec15037.png">
Є 2 списка
1, 2,  3
3, 4, 5
унікальні тут числа 1, 2, 4, 5.  
і їх 4 а не 5

**Comment by xDarkin** [comment]
Досадная ошибка. Я неверно понял задание. Решил, что надо подсчитать все имеющиеся цифры без учета повторных.
Исправил.
