### ISSUE TITLE
очікується куб :)

### ISSUE THREAD

**Issue by Muxamedin** [xDarkin/HW_GitHub#4]
https://github.com/xDarkin/HW_GitHub/blob/6cf318cea2ebce64e9b458a7ec7cd5115f5e3823/lesson_9/task_3.py#L2
<img width="780" alt="image" src="https://user-images.githubusercontent.com/4419752/185789715-16d8adcf-a4f6-40f8-bc39-6f0dde5b2d8f.png">

**Comment by xDarkin** [comment]
Исправил
