### ISSUE TITLE
Функція не має параметрів 

### ISSUE THREAD

**Issue by Muxamedin** [xDarkin/HW_GitHub#5]
https://github.com/xDarkin/HW_GitHub/blob/a24942c465e41ef492c4298a7c2ea005f89ecd74/lesson_11/task_1.py#L2

Функція не має параметрів/аргументів
хоча 
<img width="754" alt="image" src="https://user-images.githubusercontent.com/4419752/186757271-1eadac5d-08fd-4db4-9211-91863a382141.png">

**Comment by xDarkin** [comment]
Подправил
